---
aws:
  access_key_id : 'ACCESS KEY ID'
  secret_access_key : 'ACCESS KEY'
  volume_tag : 'Snapper' # tag to use in AWS for the EBS backup flags
  retain : '10.days'
log_to: '/var/log/ebs_snapper.log'
pause_time: 1